# Generated by Django 3.0.7 on 2021-11-16 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 16, 15, 24, 55, 427492)),
        ),
    ]
