# Generated by Django 3.0.7 on 2021-11-09 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('NE', 'Nebraska'), ('FL', 'Florida'), ('KY', 'Kentucky'), ('WA', 'Washington'), ('WY', 'Wyoming'), ('NY', 'New York'), ('AL', 'Alabama'), ('ND', 'North Dakota'), ('VT', 'Vermont'), ('CT', 'Connecticut'), ('KS', 'Kansas'), ('DE', 'Delaware'), ('NV', 'Nevada'), ('OR', 'Oregon'), ('AK', 'Alaska'), ('MA', 'Massachusetts'), ('OH', 'Ohio'), ('MS', 'Mississippi'), ('PA', 'Pennsylvania'), ('SD', 'South Dakota'), ('CO', 'Colorado'), ('RI', 'Rhode Island'), ('DC', 'District Of Columbia'), ('TX', 'Texas'), ('UT', 'Utah'), ('ME', 'Maine'), ('NC', 'North Carolina'), ('MD', 'Maryland'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('CA', 'California'), ('AZ', 'Arizona'), ('MO', 'Missouri'), ('NJ', 'New Jersey'), ('NH', 'New Hampshire'), ('NM', 'New Mexico'), ('IL', 'Illinois'), ('LA', 'Louisiana'), ('MT', 'Montana'), ('MI', 'Michigan'), ('TN', 'Tennessee'), ('WV', 'West Virginia'), ('SC', 'South Carolina'), ('WI', 'Wisconsin'), ('VA', 'Virginia'), ('GA', 'Georgia'), ('MN', 'Minnesota'), ('ID', 'Idaho'), ('AR', 'Arkansas'), ('OK', 'Oklahoma'), ('IN', 'Indiana')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], verbose_name='year')),
                ('condition', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('car_photo', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('car_photo_1', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('car_photo_2', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('car_photo_3', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('car_photo_4', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('features', models.CharField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=100)),
                ('body_style', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('interior', models.CharField(max_length=100)),
                ('miles', models.IntegerField()),
                ('doors', models.IntegerField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')])),
                ('passengers', models.IntegerField()),
                ('vin_no', models.CharField(max_length=100)),
                ('milage', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('no_of_owners', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 9, 22, 54, 46, 693213))),
            ],
        ),
    ]
