# Generated by Django 3.0.7 on 2021-11-15 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211110_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 16, 0, 36, 26, 259265)),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(choices=[(2, '2'), (6, '6'), (4, '4'), (3, '3'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('NH', 'New Hampshire'), ('NV', 'Nevada'), ('NJ', 'New Jersey'), ('IN', 'Indiana'), ('OR', 'Oregon'), ('WI', 'Wisconsin'), ('VT', 'Vermont'), ('FL', 'Florida'), ('ND', 'North Dakota'), ('ME', 'Maine'), ('NE', 'Nebraska'), ('UT', 'Utah'), ('KS', 'Kansas'), ('WY', 'Wyoming'), ('DC', 'District Of Columbia'), ('SC', 'South Carolina'), ('HI', 'Hawaii'), ('AZ', 'Arizona'), ('MO', 'Missouri'), ('PA', 'Pennsylvania'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('LA', 'Louisiana'), ('CO', 'Colorado'), ('RI', 'Rhode Island'), ('AL', 'Alabama'), ('MS', 'Mississippi'), ('TX', 'Texas'), ('WV', 'West Virginia'), ('ID', 'Idaho'), ('DE', 'Delaware'), ('NC', 'North Carolina'), ('AR', 'Arkansas'), ('MT', 'Montana'), ('OH', 'Ohio'), ('NM', 'New Mexico'), ('IA', 'Iowa'), ('MN', 'Minnesota'), ('OK', 'Oklahoma'), ('GA', 'Georgia'), ('IL', 'Illinois'), ('VA', 'Virginia'), ('CA', 'California'), ('WA', 'Washington'), ('TN', 'Tennessee'), ('SD', 'South Dakota'), ('CT', 'Connecticut'), ('KY', 'Kentucky'), ('MI', 'Michigan'), ('AK', 'Alaska'), ('NY', 'New York')], max_length=100),
        ),
    ]
