# Generated by Django 3.0.7 on 2021-11-16 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20211116_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 16, 10, 35, 14, 380831)),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(choices=[(2, '2'), (6, '6'), (5, '5'), (4, '4'), (3, '3')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('GA', 'Georgia'), ('PA', 'Pennsylvania'), ('HI', 'Hawaii'), ('OH', 'Ohio'), ('WA', 'Washington'), ('SD', 'South Dakota'), ('NC', 'North Carolina'), ('MD', 'Maryland'), ('TN', 'Tennessee'), ('WI', 'Wisconsin'), ('NM', 'New Mexico'), ('MA', 'Massachusetts'), ('AK', 'Alaska'), ('ME', 'Maine'), ('LA', 'Louisiana'), ('MO', 'Missouri'), ('NV', 'Nevada'), ('CO', 'Colorado'), ('NE', 'Nebraska'), ('OK', 'Oklahoma'), ('DC', 'District Of Columbia'), ('MS', 'Mississippi'), ('SC', 'South Carolina'), ('WV', 'West Virginia'), ('FL', 'Florida'), ('TX', 'Texas'), ('IL', 'Illinois'), ('KY', 'Kentucky'), ('ID', 'Idaho'), ('MT', 'Montana'), ('UT', 'Utah'), ('AR', 'Arkansas'), ('IN', 'Indiana'), ('OR', 'Oregon'), ('WY', 'Wyoming'), ('VT', 'Vermont'), ('NH', 'New Hampshire'), ('IA', 'Iowa'), ('RI', 'Rhode Island'), ('MN', 'Minnesota'), ('DE', 'Delaware'), ('VA', 'Virginia'), ('CA', 'California'), ('KS', 'Kansas'), ('CT', 'Connecticut'), ('NJ', 'New Jersey'), ('ND', 'North Dakota'), ('AZ', 'Arizona'), ('NY', 'New York'), ('MI', 'Michigan')], max_length=100),
        ),
    ]
