# Generated by Django 3.0.7 on 2021-11-16 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20211116_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 16, 13, 15, 49, 734464)),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(choices=[(6, '6'), (2, '2'), (4, '4'), (3, '3'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('TX', 'Texas'), ('ID', 'Idaho'), ('NM', 'New Mexico'), ('VA', 'Virginia'), ('CA', 'California'), ('OR', 'Oregon'), ('ND', 'North Dakota'), ('LA', 'Louisiana'), ('AR', 'Arkansas'), ('CO', 'Colorado'), ('VT', 'Vermont'), ('AL', 'Alabama'), ('KY', 'Kentucky'), ('HI', 'Hawaii'), ('MI', 'Michigan'), ('AZ', 'Arizona'), ('NY', 'New York'), ('RI', 'Rhode Island'), ('IL', 'Illinois'), ('GA', 'Georgia'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MS', 'Mississippi'), ('IA', 'Iowa'), ('NH', 'New Hampshire'), ('NE', 'Nebraska'), ('MA', 'Massachusetts'), ('AK', 'Alaska'), ('PA', 'Pennsylvania'), ('WY', 'Wyoming'), ('MT', 'Montana'), ('DC', 'District Of Columbia'), ('WI', 'Wisconsin'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('ME', 'Maine'), ('NC', 'North Carolina'), ('UT', 'Utah'), ('MD', 'Maryland'), ('DE', 'Delaware'), ('OH', 'Ohio'), ('NJ', 'New Jersey'), ('TN', 'Tennessee'), ('WV', 'West Virginia'), ('CT', 'Connecticut'), ('OK', 'Oklahoma'), ('WA', 'Washington'), ('NV', 'Nevada'), ('FL', 'Florida')], max_length=100),
        ),
    ]
