# Generated by Django 3.0.7 on 2021-11-16 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20211116_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 16, 15, 24, 55, 536839)),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(choices=[(4, '4'), (3, '3'), (6, '6'), (2, '2'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('OK', 'Oklahoma'), ('ID', 'Idaho'), ('PA', 'Pennsylvania'), ('NH', 'New Hampshire'), ('MN', 'Minnesota'), ('NE', 'Nebraska'), ('OH', 'Ohio'), ('AK', 'Alaska'), ('IL', 'Illinois'), ('GA', 'Georgia'), ('NY', 'New York'), ('CO', 'Colorado'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('IN', 'Indiana'), ('NM', 'New Mexico'), ('CA', 'California'), ('AR', 'Arkansas'), ('TX', 'Texas'), ('RI', 'Rhode Island'), ('DE', 'Delaware'), ('AL', 'Alabama'), ('MT', 'Montana'), ('MI', 'Michigan'), ('UT', 'Utah'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('MS', 'Mississippi'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('AZ', 'Arizona'), ('ND', 'North Dakota'), ('MA', 'Massachusetts'), ('WV', 'West Virginia'), ('TN', 'Tennessee'), ('MD', 'Maryland'), ('CT', 'Connecticut'), ('NJ', 'New Jersey'), ('DC', 'District Of Columbia'), ('FL', 'Florida'), ('MO', 'Missouri'), ('NC', 'North Carolina'), ('KS', 'Kansas'), ('SC', 'South Carolina'), ('VT', 'Vermont'), ('KY', 'Kentucky'), ('WA', 'Washington'), ('NV', 'Nevada'), ('SD', 'South Dakota'), ('VA', 'Virginia'), ('OR', 'Oregon')], max_length=100),
        ),
    ]
